### ISSUE TITLE
PCB BOM

### ISSUE THREAD

**Issue by glee263** [zhe-ch/ACTEV#1]
Hello,

We wish to fabricate your ethernet PCB interface. According to your published image, there are parts for U6, U7, and J4. However, I cannot see those in your shared folder. Is it okay to work without these?

Thanks in advance!

Best wishes,
Gichan

**Comment by zhe-ch** [comment]
Hi Gichan, I believe the U6, U7, and J4 parts are needed. I updated the schematic:
https://github.com/zhe-ch/ACTEV/tree/main/PCB/Schematic
Hope this can help!

**Comment by glee263** [comment]
Thank you so much for sharing the schematic!
I also have another question to fabricate PCB. I can see G1, G2, P1, and P2 copper layers. Is there order to assemble these layers?

Best,
Gichan

**Comment by zhe-ch** [comment]
Hi Gichan,

You could try putting G1 - L2, P1 - L3, P2 - L4, G2 - L5 for the assembly.
