### ISSUE TITLE
DAQ / PCB wiring instructions

### ISSUE THREAD

**Issue by glee263** [zhe-ch/ACTEV#2]
Hello,

In your eLife paper, you said that the instructions for wiring DAQ and PCB board are available here, but I cannot find it.

Could you please guide me to the instructions please?

Thank you!
Best wishes,
Gichan

**Comment by zhe-ch** [comment]
The Miniscope DAQ PCB schematic can be found here:
https://github.com/daharoni/Miniscope_DAQ_PCB/tree/master/v3_2
In our demonstration, the Miniscope DAQ is connected to interface PCB using fly wires.
Please feel free to send me email (zhechen@ucla.edu) for detailed instructions.
